# 1번

In [6]:
nums = [100, 200, 300, 400, 500]

In [2]:
# 정답1
nums.pop()
nums.pop()

400

In [4]:
# 정답2
nums[:3]

[100, 200, 300]

In [5]:
nums = [100, 200, 300, 400, 500]
nums[-5:-2]

[100, 200, 300]

# 2번

In [ ]:
l = [200, 100, 300]
l.insert(2, 10000)
print(l)

[200, 100, 10000, 300]


In [ ]:
# l[:2] + [10000] + l[-1] #error
l[:2] + [10000] + [l[-1]]

[200, 100, 10000, 300]

# 5번

In [ ]:
a = 10
b = 2
for i in range(1, 5, 2):
    a += i

print(a + b)

16


# 6번

In [ ]:
# 다음중 True인 것은? 2번
# 1)  None
# 2)  1
# 3)  ""
# 4)  0
# 5)  bool(0)

In [ ]:
bool([]) # False
bool([1, 2, 3]) # True

True

In [ ]:
# l의 값이 변한 적이 있다? 없다. 그런데 왜 bool 값은 변했을까?
l = []
print(id(l))
print(bool(l))

135380548677760
False


In [ ]:
l.append(10)
l
print(id(l))
print(bool(l))

135380548677760
True


In [ ]:
# Python은 지극히 인간의 입장에서 출력을 고려한 것입니다.

In [ ]:
l = '' #immutable
print(id(l))
print(bool(l))

135380976959536
False


In [ ]:
l = 'a'
print(id(l))
print(bool(l))

135380975746480
True


#7번

In [ ]:
# 언더바 변수에 대하여
# 반복문 등에서 사용하지 않는 변수에 _를 넣습니다.
for _ in range(5):
    print('hello')

# 프라이빗한 변수에서 _를 사용합니다.
class Human():
    _age = 0

hello
hello
hello
hello
hello


# 8번

In [ ]:
d = {'height':180,
     'weight':78,
     'weight':84,
     'temparture':36,
     'eyesight':1}
print(d['weight'])

84


# 9번

In [ ]:
year = '2019'
month = '04'
day = '26'
hour = '11'
minute = '34'
second = '27'

print(year, month, day, sep='/', end=' ')
print(hour, minute, second, sep=':')

2019/04/26 11:34:27


# 10번

In [ ]:
#     *
#    ***
#   *****
#  *******
# *********

In [ ]:
n = 5
for i in range(1, n+1):
    print(i)

1
2
3
4
5


In [ ]:
n = 5
for i in range(1, n + 1):
    print(((n - i) * ' ') + '*')

    *
   *
  *
 *
*


In [ ]:
n = 5
for i in range(1, n + 1):
    print(((n - i) * ' ') + (((2 * i) - 1)) * '*')

    *
   ***
  *****
 *******
*********


# 11번

In [ ]:
s = 0
for i in range(1, 101):
    s += i
print(s)

5050


# 12번

In [ ]:
class Wizard:
    def __init__(self, health, mana, armor):
        '''
        self는 인스턴스, 인스턴스 메모리 영역
        '''
        self.health = health
        self.mana = mana
        self.armor = armor

    def attack(self):
        print('파이어볼')


jik = Wizard(health = 545, mana = 210, armor = 10)
print(jik.health, jik.mana, jik.armor)
jik.attack()

545 210 10
파이어볼


# 14번
문제가 너무 쉬워 아래 문제로 풀도록 하겠습니다.

* 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/120871?language=javascript

In [ ]:
# 이러한 조건 문제에서 문제가 쉽게 풀리지 않을 경우
# 소거법을 사용하시는 방법으로 푸시면 좀 더 쉽게 풀 수도 있습니다.

[i for i in range(100) if i % 3 != 0] # 3의 배수 제거!
[i for i in range(100) if '3' not in str(i)] # 3이 들어가 있는 숫자 제거!

[i for i in range(100) if i % 3 != 0 and '3' not in str(i)][9-1]
[i for i in range(100) if i % 3 != 0 and '3' not in str(i)][10-1]

solution = lambda n:[i for i in range(10000) if i % 3 != 0 and '3' not in str(i)][n-1]
solution(9)

14

# 16번

In [ ]:
'안녕하세요'[::-1]

'요세하녕안'

In [ ]:
''.join(list(reversed(list('안녕하세요'))))

'요세하녕안'

In [ ]:
s = '안녕하세요'
ss = list(s)
ss.reverse()
''.join(ss)

'요세하녕안'

In [ ]:
s = '안녕하세요'
result = ''
for i in s:
    result = i + result
result

'요세하녕안'

In [ ]:
def reverse(s):
    if len(s) == 1:
        return s
    else:
        return reverse(s[1:]) + s[0]

reverse('안녕하세요')

'요세하녕안'

# 17번

In [ ]:
height = 150

if height >= 150: print('YES')

YES


In [ ]:
height = 149

# print('NO') if height >= 150: print('YES') # Error
print('YES') if height >= 150 else print('NO')

NO


In [ ]:
def solution(height):
    return 'YES' if height >= 150 else 'NO'

solution(150)

'YES'

# 18번

In [ ]:
list(map(int, '20 30 40'.split(' ')))

[20, 30, 40]

In [ ]:
sum(map(int, '20 30 40'.split(' '))) / 3

30.0

# 21번

In [ ]:
# 1)  x = {1, 2, 3, 5, 6, 7}
# 2)  x = {} # dict
# 3)  x = set('python')
# 4)  x = set(range(5))
# 5)  x = set()

In [ ]:
t = 1
t = (1) # tuple 아님!
t = (1,)
t

# 어떤 라이브러리나 프레임웤 마지막 콤마가 꼭 있는 이유(3 ~ 4개 있습니다.)
# 버전관리하는 곳에서 콤마를 버전의 업이라고 인식하는 경우가 있습니다.
# Ctrl + C, V
# 튜플인경우 상수, 문자가 들어갔을 때 튜플이 아닌 int, str로 변환되는 것을 막기 위해
옵션 = (
    'a',
)

# 24번

In [ ]:
'mary'.upper()

'MARY'

In [ ]:
ord('a')

97

In [ ]:
ord('A')

65

In [ ]:
ord('a') - ord('A')

32

In [ ]:
ord('a') - 32

65

In [ ]:
chr(ord('a') - 32)

'A'

In [ ]:
for i in 'mary':
    print(chr(ord(i) - 32), end='') # 완벽한 코드는 아니고, 소문자인 것을 판단하는 if가 위에 있어야 합니다.

MARY

In [ ]:
# 도대체 이런 지식은 어디에 쓸모가 있을까요? 인코딩쪽에서 어떤 인코딩인지 확인하는 용도로 사용하기도 합니다.
# 알고리즘은 얼마나 쓸모가 있나요? 코드를 읽는 속도와 이해하는 속도에 도움을 줍니다.
# => 코드는 AI가 더 잘짭니다.ㅎㅎ 잘 짠것을 확인해주는 작업은 내가 해야 합니다.

# 26번 문제

In [ ]:
key = '수성, 금성, 지구, 화성, 목성, 토성, 천왕성, 해왕성'.split(', ')
value = 'Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune'.split(', ')

In [ ]:
dict(zip(key, value))

{'수성': 'Mercury',
 '금성': 'Venus',
 '지구': 'Earth',
 '화성': 'Mars',
 '목성': 'Jupiter',
 '토성': 'Saturn',
 '천왕성': 'Uranus',
 '해왕성': 'Neptune'}

# 28번

In [ ]:
s = 'python'
for i in range(len(s)-1): # 아래 zip에서는 -1을 고려하지 않아도 됩니다.
    print(s[i:i+2])

py
yt
th
ho
on


In [ ]:
s = 'python'
list(zip(s, s[1:])) # 짝이 안맞으면 어차피 생성하지 않습니다.

[('p', 'y'), ('y', 't'), ('t', 'h'), ('h', 'o'), ('o', 'n')]

In [ ]:
s = 'python'
for i in zip(s, s[1:]):
    print(''.join(i))

py
yt
th
ho
on


In [ ]:
s = 'life is short, you need python'
for i in range(len(s)-2): # zip에서는 -2을 고려하지 않아도 됩니다.
    print(s[i:i+3])

lif
ife
fe 
e i
 is
is 
s s
 sh
sho
hor
ort
rt,
t, 
, y
 yo
you
ou 
u n
 ne
nee
eed
ed 
d p
 py
pyt
yth
tho
hon


In [ ]:
p = [1, 3, 5, 7, 11, 14, 19, 21, 22]
list(zip(p, p[1:]))
list(map(lambda x:x[1]-x[0], zip(p, p[1:])))

[2, 2, 2, 4, 3, 5, 2, 1]

# 29번
* 문제 변경: 대문자만 지나가도록 코딩해주세요. 'HellO WoRld' -> HOR

In [ ]:
for s in 'HellO WoRld':
    if s != s.lower():
        print(s)

H
O
W
R


In [ ]:
for s in 'HellO WoRld':
    if 'A' <= s <= 'Z':
        print(s)

H
O
W
R


In [ ]:
for s in 'HellO WoRld':
    if s.isupper(): # 서영님께서 말씀해주신 코드가 가장 좋은 코드라고 생각합니다.
        print(s)

H
O
W
R


# 30번

In [ ]:
'pineapple is yummy apple'.find('apple') # 없는 것을 찾을 때 -1
'pineapple is yummy apple'.index('xpple') # 없는 것을 찾을 때 error <- error가 나면 서비스 멈춥니다!
# 예를 들어 주기적으로 크롤링하는 코드가 있다면
# find를 쓰셔서 error가 안나고 다음 코드로 넘어가게 코딩하실 수 있습니다.
# 예외처리를 하는 것이 가장 좋습니다.
# 정답: 목적에 맞게 사용하셔야 합니다.

ValueError: ignored

In [ ]:
'pineapple is yummy apple'.rfind('apple')
'pineapple is yummy apple'.rindex('apple')

19

In [ ]:
'pineapple is yummy apple'.find('apple', 10)
'pineapple is yummy apple'.index('apple', 10)

19

# 31번


In [ ]:
# https://wayhome25.github.io/python/2017/06/14/time-complexity/
# 1)  l[i]
# 2)  l.append(5)
# 3)  l[a:b] # 정답
# 4)  l.pop()
# 5)  l.clear()

In [ ]:
# 그럼에도 불구하고 슬라이싱을 사용해야 할 경우
# error를 발생시키지 않기 때문에

l = [1, 2, 3, 4, 5]

# l[10]  # out of range error!
l[10:11] # out of range error가 안남! 그런데 기능은 같음!

[]

# 35번

In [ ]:
# 매우매우 중요한 내용

def one(n):
    def two(value):
        return value ** n
    return two

a = one(2)
b = one(3)
c = one(4)
print(a(10))
print(b(10))
print(c(10))

100
1000
10000


In [ ]:
# 객체지향 프로그래밍 예제
class Book:
    def __init__(self, title, content, author, pub_date):
        self.title = title
        self.content = content
        self.author = author
        self.pub_date = pub_date

    def calculate_date(self):
         self.pub_date - self.current_date

In [ ]:
# 1. 함수를 변수에 할당할 수 있습니다.
# 2. 함수를 데이터 구조에 저장할 수 있습니다.
# 3. 함수를 인자로 다른 함수에 전달할 수 있습니다.
# 4. 함수를 결과로서 반환할 수 있습니다.

In [ ]:
def add(x, y):
    return x + y
x = add
x(10, 20)

30

In [ ]:
id(x), id(add)

(135380548703216, 135380548703216)

In [ ]:
def add():
    return lambda x: x**2
x = add()
x(10)

100

In [69]:
# 데코레이터
def simple_decorator(function):
    def wrapper():
        print("Before the function call")
        function()
        print("After the function call")
    return wrapper

@simple_decorator
def hello():
    print("Hello, World!")

hello() # 데코레이터가 없는 상태에서는 simple_decorator(hello)() 와 같습니다.


Before the function call
Hello, World!
After the function call


In [70]:
# 데코레이터 활용 1
def simple_decorator(function):
    def wrapper(l):
        print("Before the function call")
        print(function(map(int, l)))
        print("After the function call")
    return wrapper

@simple_decorator
def 합(l):
    return sum(l)

합([1, 2, 3, '4'])

Before the function call
10
After the function call


In [71]:
# 데코레이터 활용 2
def debug(function):
    def new_function(*args):
        print(f'{function.__name__} 함수 시작')
        print(*args)
        result = function(*args)
        print(f'{function.__name__} 함수 끝')
        # return result # return 값이 있는 데코레이터는 바로 뒤에서 진행합니다.

    return new_function


@debug
def sum_1_to_n(n):
    return n * (n + 1) / 2


result = sum_1_to_n(30)

print(result)

sum_1_to_n 함수 시작
30
sum_1_to_n 함수 끝
None


In [72]:
# *agrs: 변수가 여러개와도 받음
def test(*args):
    for i in args:
        print(i)

test(1, 2, 3, 4, 5, 'hello world')

1
2
3
4
5
hello world


In [78]:
# **kagrs: 키워드 아규먼츠

def test(**kargs):
    print(kargs)
    for i in kargs:
        print(i)

test(one=1, two=2)


{'one': 1, 'two': 2}
one
two


In [79]:
# 데코레이터 활용 3
def decorator1(function):
    def new_function(*args, **kwargs):
        print('첫번째 데코레이터 시작')
        result = function(*args, **kwargs)
        print('첫번째 데코레이터 끝')
        return result

    return new_function


def decorator2(function):
    def new_function(*args, **kwargs):
        print('두번째 데코레이터 시작')
        result = function(*args, **kwargs)
        print('두번째 데코레이터 끝')
        return result

    return new_function


def decorator3(function):
    def new_function(*args, **kwargs):
        print('세번째 데코레이터 시작')
        result = function(*args, **kwargs)
        print('세번째 데코레이터 끝')
        return result

    return new_function

@decorator1
@decorator2
@decorator3
def sum_1_to_n(n):
    return n * (n + 1) / 2

result = sum_1_to_n(30)

print(f'result: {result}')

첫번째 데코레이터 시작
두번째 데코레이터 시작
세번째 데코레이터 시작
세번째 데코레이터 끝
두번째 데코레이터 끝
첫번째 데코레이터 끝
result: 465.0


In [ ]:
# 동적 데코레이터
def add(n):
    def decorator(function):
        def new_function(*args, **kwargs):
            result = function(*args, **kwargs)
            return result + n
        return new_function
    return decorator

@add(10)
def plus(a, b):
    return a + b

result = plus(10, 20)
print(f'result : {result}')

# 36번

In [ ]:
# 1~9까지의 숫자 중 하나를 입력하면 그 단의 구구단 결과를 한 줄에 출력하는 프로그램을 작성하세요.


# 37번
* 문제 변경


In [80]:
# 1부터 10000까지 8이라는 숫자를 count하라!
# count를 할 수 있는 자료형으로 만드는 것이 핵심!
# 순회를 돌면서 count는 위 답안이 안풀렸을 때 대안 정도 가능함.
str(list(range(10000))).count('8')

4000

# 38번
```
점수입력 : 97 86 75 66 55 97 85 97 97 95

출력 : 6
```

In [113]:
sorted(map(int, '97 86 75 66 55 97 85 97 97 95'.split(' ')), reverse=True)
# str -> list

[97, 97, 97, 97, 95, 86, 85, 75, 66, 55]

In [114]:
sorted(set(map(int, '97 86 75 66 55 97 85 97 97 95'.split(' '))), reverse=True)[3]
# 3위 점수

85

In [115]:
count = 0
for i in sorted(map(int, '97 86 75 66 55 97 85 97 97 95'.split(' ')), reverse=True):
    if i == sorted(set(map(int, '97 86 75 66 55 97 85 97 97 95'.split(' '))), reverse=True)[3]:
        break
    else:
        count += 1
print(count)

6


In [116]:
# 내 답
점수 = '97 86 75 66 55 97 85 97 97 95'
count=0
점수2 = sorted(set(map(int, 점수.split(' '))), reverse=True)[3]
for i in sorted(map(int, 점수.split(' ')), reverse=True):
    if i == 점수2:
        break
    else:
        count += 1
print(count)


6


In [118]:
# 강사님 답 (1자리 점수가 있을때 오류가 발생)
def solution(s):
    answer = 0
    splitdata = map(int, s.split(' '))
    for i in list(reversed(sorted(set(splitdata))))[:3]:
        answer += s.count(str(i))
    return answer

solution('97 86 75 66 55 97 85 97 97 95')

6

In [119]:
def solution(s):
    answer = 0
    splitdata = list(map(int, s.split(' ')))
    for i in list(reversed(sorted(set(splitdata))))[:3]:
        for j in list(splitdata):
            if i == j:
                answer += 1
    return answer

solution('97 86 75 66 55 97 85 97 97 95')

6

In [120]:
# map으로 된 데이터가 왜 한 번만 순회가 되었는지
# https://www.notion.so/paullabworkspace/python-zip-b7a1992be7884891a5f1d0a5c0c2df9c?pvs=4

def solution(s):
    answer = 0
    splitdata = map(int, s.split(' '))
    for i in list(reversed(sorted(set(splitdata))))[:3]:
        print(list(splitdata))
        for j in list(splitdata):
            if i == j:
                answer += 1
    return answer

solution('97 86 75 66 55 97 85 97 97 95')

[]
[]
[]


0

In [121]:
import collections

collections.Counter('97 86 75 66 55 97 85 97 97 95'.split(' '))

Counter({'97': 4, '86': 1, '75': 1, '66': 1, '55': 1, '85': 1, '95': 1})

# 39번

```
입력 : querty
출력 : euerty

입력 : hqllo my bamq is hyqwob
출력 : hello my bame is hyewob
```

In [133]:
'qurety'.replace('q', 'e').replace('b', 'n')

'eurety'

In [136]:
import re
def solution(s):
    return re.sub('e', 'q',re.sub('q', 'e', s))
solution('hqllo my bamq is hyqwob')

'hqllo my bamq is hyqwob'

In [ ]:
re.sub(r'[qb]', lambda x: 'e' if x.group() == 'q' else 'n', s)

# 41번
- 1과 자기 자신만을 약수로 가지는 수


In [137]:
for i in range(2, 997):
    if 997 % i == 0:
        print('소수가 아닙니다!')
        break

In [140]:
def prime_list(n):
    # 에라토스테네스의 체 초기화: n개 요소에 True 설정(소수로 간주)
    sieve = [True] * n

    # n의 최대 약수가 sqrt(n) 이하이므로 i=sqrt(n)까지 검사
    m = int(n ** 0.5)
    for i in range(2, m + 1):
        if sieve[i] == True:           # i가 소수인 경우
            for j in range(i+i, n, i): # i이후 i의 배수들을 False 판정
                sieve[j] = False

    # 소수 목록 산출
    return [i for i in range(2, n) if sieve[i] == True]
prime_list(100)

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

In [ ]:
def prime_list(n):
    # 에라토스테네스의 체 초기화: n개 요소에 True 설정(소수로 간주)
    sieve = [True] * n

    # n의 최대 약수가 sqrt(n) 이하이므로 i=sqrt(n)까지 검사
    m = int(n ** 0.5)
    for i in range(2, m + 1):
        if sieve[i] == True:           # i가 소수인 경우
            for j in range(i+i, n, i): # i이후 i의 배수들을 False 판정
                sieve[j] = False

    print(sieve) # 0부터 시작해서 i가 소수인경우 True

    # 소수 목록 산출
    return [i for i in range(2, n) if sieve[i] == True]

prime_list(100)

# 43번

In [152]:
# 음수 변환까지 하려면 좀 더 고려를 해야 합니다.
x = 11
s = ''
while x:
    print(x)
    s += str(x % 2)
    x //= 2
s[::-1]

#   2   | 11 ... 1
#        ---
#   2   |  5 ... 1
#        ---
#   2   |  2 ... 0
#        ---
#   2   |  1

11
5
2
1


'1011'

# 44번


In [154]:
# 예를들어
# 18234 = 1+8+2+3+4 이고 정답은 18 입니다.
# 3849 = 3+8+4+9 이고 정답은 24입니다.


n = 1234
answer = 0
for i in str(n):
    answer += int(i)
answer

10

# 45번

1

# 48번

In [155]:
# 다시 확인 필요
s = 'AAABBBcccddd'
answer = ''
for i in s:
    if s.isupper():
        answer += i.lower()
    else:
        answer += i.upper()
answer


'AAABBBCCCDDD'

# 53번
괄호 문자열이란 괄호 기호인 '{', '}', '[', ']', '(', ')' 와 같은 것을 말한다. 그 중 괄호의 모양이 바르게 구성 된 문자열을 바른 문자열, 그렇지 않은 문자열을 바르지 않은 문자열이라 부르도록 하자.

(())와 같은 문자열은 바른 문자열이지만 ()()) 와 같은 문자열은 바르지 않은 문자열이다.(해당 문제에서는 소괄호만 판별하지만, 실력이 되시는 분들은 중괄호와 대괄호까지 판별해보세요.)

입력으로 주어진 괄호 문자열이 바른 문자열인지 바르지 않은 문자열인지 "YES"와 "NO"로 구분된 문자열을 출력해보자.

In [165]:
s1 = '()())'
s2 = '(0)'

answer = ''

for i in s:
    if i in '(':
        answer += i
    elif i in ')':
        if not answer or answer[-1] != ')':
            print('No')
            break



# 54번


In [168]:

s1 = '1 2 3 4 5'
s2 = '1 4 2 6 3'
def solution(s):
    a = sorted(list(map(int, s.split(' '))))
    if a == list(range(min(a), max(a)+1)):
        return 'YES'
    else:
        return 'NO'

solution(s1)


[1, 2, 3, 4, 5]

# 55번

재귀로 풉니다.

한쪽 기둥에서 다른 마지막 기둥으로 모두 옮기는 것이 중요합니다.

In [188]:
# [[A, C], [A, B] c,b a,c b,a b,c a,c]]
원판의이동경로 = []
def 하노이(원반의수, 시작기둥, 목표기둥, 보조기둥):
    #원판이 한개일 때에는 옮기면 됩니다.
    if 원반의수 == 1:
        원판의이동경로.append([시작기둥, 목표기둥])
        return None
    #원반의 n-1개를 경유기둥으로 옮기고
    하노이(원반의수 - 1, 시작기둥, 보조기둥, 목표기둥)
    #가장 큰 원반은 목표기둥으로
    원판의이동경로.append([시작기둥, 목표기둥])
    #경유기둥과 시작기둥을 바꿉니다!
    하노이(원반의수 - 1, 보조기둥, 목표기둥, 시작기둥)

하노이(3, 'A','C','B')

print(len(원판의이동경로))
원판의이동경로

7


[['A', 'C'],
 ['A', 'B'],
 ['C', 'B'],
 ['A', 'C'],
 ['B', 'A'],
 ['B', 'C'],
 ['A', 'C']]

# 56번

다음의 딕셔너리가 주어졌을 때 한국의 면적과 가장 비슷한 국가와 그 차이를 출력하세요.


```
데이터
nationWidth = {
     'korea': 220877,
     'Rusia': 17098242,
     'China': 9596961,
     'France': 543965,
     'Japan': 377915,
     'England' : 242900 }

출력
England 22023
```

In [208]:
nationWidth = {
     'korea': 220877,
     'Rusia': 17098242,
     'China': 9596961,
     'France': 543965,
     'Japan': 377915,
     'England' : 242900 }

a = nationWidth['korea']
nationWidth.pop('korea')
gap = float('inf')
answer = ''
for nation, value in nationWidth.items():
    if abs(a - value) < gap:
        gap = abs(a - value)
        answer = nation

print(answer, gap)

England 22023


In [269]:
nationWidth = {
     'Rusia': 17098242,
     'China': 9596961,
     'France': 543965,
     'Japan': 377915,
     'England' : 242900 }

def f(key):
    return [nationWidth[key] - 220877, key]
min(map(f, nationWidth))

[22023, 'England']

In [274]:
nationWidth = {
     'Rusia': 17098242,
     'China': 9596961,
     'France': 543965,
     'Japan': 377915,
     'England' : 242900 }

min(map(lambda key: [nationWidth[key] - 220877, key], nationWidth))[1]

'England'

# 57번

0부터 1000까지 1의 개수를 세는 프로그램을 만들려고 합니다. 예를 들어 0부터 20까지 1의 개수를 세어본다면 1, 10 11, 12, 13, 14, 15, 16, 17, 18, 19 에 각각 1이 들어가므로 12개의 1이 있게 됩니다. 11은 1이 2번 들어간 셈이죠.

그렇다면 0부터 1000까지 수에서 1은 몇번이나 들어갔을까요? 출력해주세요!

In [210]:
str(list(range(0, 1001))).count('1')

301

# 58번

원범이는 편의점 아르바이트가 끝난 후 정산을 하고자 합니다.
정산을 빨리하고 집에가고 싶은 원범이는 프로그램을 만들려고 합니다.

숫자를 입력 받고 천단위로 콤마(,)를 찍어주세요.

예를들어, 123456789를 입력받았으면 123,456,789 를 출력해야합니다.

In [255]:
format(123456789, ',')


'123,456,789'

In [260]:
list(str(123456789))

['1', '2', '3', '4', '5', '6', '7', '8', '9']

# 59번

총 문자열의 길이는 50으로 제한하고 사용자가 문자열을 입력하면 그 문자열을 가운데 정렬을 해주고, 나머지 빈 부분에는 '='을 채워넣어주세요.

```
입력
hi

출력
========================hi========================
```

In [276]:
userinput = input()
print("{0:=^50}".format(user_input))

hi
========================hi========================


In [282]:
userinput = 'hi'
print(f'{userinput:=<50}')

hi================================================


In [283]:
print(f'{userinput:=>50}')


================================================hi


In [284]:
print(f'{userinput:=^50}')


========================hi========================


# 60번

새학기가 되어 이름을 가나다 순서대로 배정하고 번호를 매기려고 합니다.

코드에 입력된 이름을 아래와 같이 출력해주세요.

In [289]:
student = ['강은지','김유정','박현서','최성훈','홍유진','박지호','권윤일','김채리','한지호','김진이','김민호','강채연']

for i, j in enumerate(sorted(student)):
    print(f'번호: {i+1}, 이름: {j}')

번호: 1, 이름: 강은지
번호: 2, 이름: 강채연
번호: 3, 이름: 권윤일
번호: 4, 이름: 김민호
번호: 5, 이름: 김유정
번호: 6, 이름: 김진이
번호: 7, 이름: 김채리
번호: 8, 이름: 박지호
번호: 9, 이름: 박현서
번호: 10, 이름: 최성훈
번호: 11, 이름: 한지호
번호: 12, 이름: 홍유진


# 61번
문자열을 입력받고 연속되는 문자열을 압축해서 표현하고싶습니다.
```
입력
aaabbbbcdddd

출력
a3b4c1d4

```

In [292]:
collections.Counter('aaabbbbcdddd').items()

dict_items([('a', 3), ('b', 4), ('c', 1), ('d', 4)])

In [307]:
from collections import Counter
answer =''
for key, value in Counter('aaabbbbcdddd').items():
    answer += key
    answer += str(value)
answer

'a3b4c1d4'

In [306]:
from collections import Counter
s = "aaabbbbcdddd"
"".join([str(i) + str(Counter(s)[i]) for i in Counter(s)])

'a3b4c1d4'

In [309]:
# 입력
# aaabbbbcddddaaabbbbcdddd

# 출력
# a3b4c1d4a3b4c1d4

s = 'aaabbbbcddddaaabbbbcdddd'
answer = ''
count = 0
pre = s[0]
for i in s:
    # print(pre, i)
    if pre == i:
        count += 1
    else:
        answer += pre + str(count)
        pre = i
        count = 1

answer += pre + str(count)

answer


'a3b4c1d4a3b4c1d4'

In [319]:
re.findall('(\\w)(\\1*)', s)

[('a', 'aa'),
 ('b', 'bbb'),
 ('c', ''),
 ('d', 'ddd'),
 ('a', 'aa'),
 ('b', 'bbb'),
 ('c', ''),
 ('d', 'ddd')]

In [315]:
import re

s = 'aaabbbbcddddaaabbbbcdddd'
answer =''
for i in re.findall('(\\w)(\\1*)', s):
    answer += i[0] + str(len(i[1])+1)
answer

'a3b4c1d4a3b4c1d4'

# 62번

`20190923`을 출력합니다.  아래 기준만 만족하면 됩니다.

1. 코드 내에 숫자가 없어야 합니다.
    - 예) print(20190923)이라고 하시면 안됩니다.
2. 파일 이름이나 경로를 사용해서는 안됩니다.
3. 시간, 날짜 함수를 사용해서는 안됩니다.
4. 에러 번호 출력을 이용해서는 안됩니다.
5. input을 이용해서는 안됩니다.

In [308]:
string='aacddddddddd'
a=string.count('a') #2
b=string.count('b') #0
c=string.count('c') #1
d=string.count('d') #9
print(int(str(a)+str(b)+str(c)+str(d)+str(b)+str(d)+str(a)+str(a+1)))

20190923


# 63번

한국대학교의 김한국교수님은 학생들과 친해지기 위해서 딸에게 줄임말을 배우기로 했습니다.
딸은 '복잡한 세상 편하게 살자' 라는 문장을 '복세편살'로 줄여 말합니다.

교수님이 줄임말을 배우기 위해 위와 같이 어떤 입력이 주어지면 앞 글자만 줄여 출력하도록 해주세요.

```
입력 - 입력은 한글 혹은 영어로 입력됩니다.
복잡한 세상 편하게 살자


출력 - 띄어쓰기를 기준으로 하여 짧은 형태로 출력합니다.
복세편살

```

In [327]:

user_input = '복잡한 세상 편하게 살자'.split(' ')
#print(user_input)
result = ''

for s in user_input:
    result += s[0]

print(result)

복세편살


# 65번

```
a = [1,2,3,4]
b = [a,b,c,d]
이런 리스트가 있을 때 [[1,a],[b,2],[3,c],[d,4]] 이런식으로 a,b리스트가 번갈아가면서 출력되게 해주세요.

```

In [337]:

a = [1, 2,3, 4]
b = ['a', 'b', 'c', 'd']

count = 0
answer = []
for i, j in zip(a, b):
    count += 1
    if count % 2 == 0:
        answer.append([j, i])
    else:
        answer.append([i, j])
answer


[[1, 'a'], ['b', 2], [3, 'c'], ['d', 4]]

# 66번

탑을 쌓기 위해 각 크기별로 준비된 블럭들을 정해진 순서에 맞게 쌓아햐 합니다.
순서에 맞게 쌓지 않으면 무너질 수 있습니다.
예를 들면 정해진 순서가 BAC 라면 A 다음 C가 쌓아져야 합니다.
선행으로 쌓아야 하는 블럭이 만족된 경우라면 탑이 무너지지 않습니다.

- B를 쌓지 않아도 A와 C를 쌓을 수 있습니다.
- B 다음 블럭이 C가 될 수 있습니다.

쌓아져 있는 블럭 탑이 순서에 맞게 쌓아져 있는지 확인하세요.

1. 블럭은 알파벳 대문자로 표기합니다.
2. 규칙에 없는 블럭이 사용될 수 있습니다.
3. 중복된 블럭은 존재하지 않습니다.

```
입력
탑 = ["ABCDEF", "BCAD", "ADEFQRX", "BEDFG"]
규칙 = "ABD"

출력
["가능","불가능","가능","가능]
```

In [11]:
# 첫번째 풀이 (박재혁)
탑 = ["ABCDEF", "BCAD", "ADEFQRX", "BEDFG"]
규칙 = "ABD"

answer = []

for t in 탑:
    규칙인덱스 = [t.index(rule) for rule in 규칙 if rule in t]
    if 규칙인덱스 == sorted(규칙인덱스):
        answer.append('가능')
    else:
        answer.append('불가능')

print(answer)

['가능', '불가능', '가능', '가능']


In [12]:
# 두번째 풀이 (김태호)
input = ["ABCDEF", "BCAD", "ADEFQRX", "BEDFG"]
rule = "ABD"

rule = list(rule)
result = list(map(lambda x: [x.find(r) for r in rule if x.find(r) != -1], input))
list(map(lambda x: '가능' if all(x[i] < x[i+1] for i in range(len(x)-1)) else '불가능', result))

['가능', '불가능', '가능', '가능']

In [14]:
# 쉬운풀이
string = ["ABCDEF", "BCAD", "ADEFQRX", "BEDFG"]
rule = "ABD"

def solution(s, rule):
    temp = 0
    for i in s: #i:'D', s:"ABCDEF"
        if i in rule:
            if temp > rule.index(i): # rule.index(i): 문자가 rule에 있다면 몇 번째에 있는지(1 > 3)
                return '불가능'
            temp = rule.index(i)
    return '가능'

solution(string[3], rule)


[0, 1, 3]
[2, 0, 3]
[0, 1]
[0, 2]


# 67번



In [ ]:
# 2명 - [a,b] 1번
# 3명 - [a, b], [a,c],[b,c] 3번
# 조합 (2명이 들어가는 조합)



In [19]:
from itertools import combinations

n = 4
nums = range(n)
combi = list(combinations(nums, 2))
combi

[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]

In [21]:
from itertools import combinations

n = 11
nums = range(n)
combi = list(combinations(nums, 2))
59 - len(combi)

4

# 68번 (풀기)

학교가 끝난 지원이는 집에 가려고 합니다. 학교 앞에 있는 버스 시간표는 너무 복잡해서 버스 도착시간이 몇 분 남았는지 알려주는 프로그램을 만들고 싶습니다.
버스시간표와 현재 시간이 주어졌을 때 버스 도착 시간이 얼마나 남았는지 알려주는 프로그램을 만들어주세요.

- 버스 시간표와 현재시간이 입력으루 주어집니다.
- 출력 포맷은 "00시00분"입니다.
   만약 1시간 3분이 남았다면 "01시간03분"으로 출력해야 합니다.
- 버스 시간표에 현재 시간보다 이전인 버스가 있다면 "지나갔습니다."라고 출력합니다.

```
입력
["12:30", "13:20", "14:13"]
"12:40"


출력
['지나갔습니다', '0시간 40분', '1시간 33분']**굵은 텍스트**

```

# 69번 (풀기)

# 70번 (풀기)


# 문제71 : 깊이 우선 탐색

**깊이 우선 탐색**이란 목표한 노드를 찾기 위해 가장 우선순위가 높은 노드의 자식으로 깊이 들어 갔다가 목표 노드가 존재하지 않으면 처음 방문한 노드와 연결된 다른 노드부터 그 자식 노드로 파고드는 검색 방법을 말합니다.


다음과 같이 리스트 형태로 노드들의 연결 관계가 주어진다고 할 때 깊이 우선 탐색으로 이 노드들을 탐색했을 때의 순서를 공백으로 구분하여 출력하는 프로그램을 완성하세요.

1. **빨간색으로 Pass라고 되어 있는 부분을 완성**해주세요.

2. **깊이 우선 탐색을 오른쪽, 왼쪽 둘 다 구현**해보세요.

3. **리스트**로도 구현해보세요.

```
1. 데이터

graph = {'E': set(['D', 'A']),
         'F': set(['D']),
         'A': set(['E', 'C', 'B']),
         'B': set(['A']),
         'C': set(['A']),
         'D': set(['E','F'])}

2. 출력
['E', 'A', 'B', 'C', 'D', 'F']

3. 코드

graph = {
        'A': set(['B', 'C', 'E']),
        'B': set(['A']),
        'C': set(['A']),
        'D': set(['E', 'F']),
        'E': set(['A', 'D']),
        'F': set(['D'])
}

def dfs(graph, start):
    visited = []
    stack = [start]

    while stack:
        n = stack.pop()
        if n not in visited:
            visited.append(n)
            pass
    return visited

print(dfs(graph, 'E'))

```

In [ ]:
graph = {
        'A': set(['B', 'C', 'E']),
        'B': set(['A']),
        'C': set(['A']),
        'D': set(['E', 'F']),
        'E': set(['A', 'D']),
        'F': set(['D'])
}

def dfs(graph, start):
    visited = []
    stack = [start]

    while stack:
        n = stack.pop()
        if n not in visited:
            visited.append(n)
            pass
    return visited

print(dfs(graph, 'E'))

In [32]:
graph = {
    'A': set(['B', 'C', 'E']),
    'B': set(['A']),
    'C': set(['A']),
    'D': set(['E', 'F']),
    'E': set(['A', 'D']),
    'F': set(['D'])
}

def dfs(graph, start):
    visited = []
    stack = [start]

    while stack:
        n = stack.pop()

        if n not in visited:
            visited.append(n)
            stack.extend(graph[n])
    return visited

print(dfs(graph, 'E'))

['E', 'D', 'F', 'A', 'C', 'B']


In [38]:
graph = {
    'A': set(['B', 'C', 'E']),
    'B': set(['A']),
    'C': set(['A']),
    'D': set(['E', 'F']),
    'E': set(['A', 'D']),
    'F': set(['D'])
}

def dfs(graph, start):
    visited = []
    stack = [start]

    while stack:
        n = stack.pop()
        if n not in visited:
            visited.append(n)
            stack += (graph[n] - set(visited))
    return visited

print(dfs(graph, 'E'))

['E', 'D', 'F', 'A', 'C', 'B']


# 72번

# 73번


# 74번


# 75번

# 76번

전쟁이 끝난 후, A나라에서는 폐허가 된 도시를 재건하려고 합니다. 그런데 이 땅은 전쟁의 중심지였으므로 전쟁 중 매립된 지뢰가 아직도 많이 남아 있었습니다. 정부는 가장 먼저 지뢰를 제거하기 위해 수색반을 꾸렸습니다.

수색반은 가장 효율적인 지뢰 제거를 하고 싶습니다. 수색반은 도시를 격자 무늬로 나눠놓고 자신들이 수색할 수 있는 범위 내에 가장 많은 지뢰가 매립된 지역을 가장 먼저 작업하고 싶습니다.

가장 먼저 테스트 케이스의 수를 나타내는 1이상 100 이하의 자연수가 주어집니다.
각 테스트 케이스의 첫 줄에는 수색할 도시의 크기 a와 수색반이 한번에 수색 가능한 범위 b가 주어집니다. (a와 b 모두 정사각형의 가로 또는 세로를 나타냅니다. 예를들어 10이 주어지면 10x10칸의 크기를 나타냅니다.)

그 후 a줄에 걸쳐 도시 내 지뢰가 있는지의 여부가 나타납니다.
0은 지뢰가 없음 1은 지뢰가 있음을 뜻합니다.

각 테스트 케이스에 대해 수색 가능한 범위 bxb 내에서 찾아낼 수 있는 가장 큰 지뢰의 갯수를 구하세요.

```
입력
1
5 3
1 0 0 1 0
0 1 0 0 1
0 0 0 1 0
0 0 0 0 0
0 0 1 0 0

출력
3

```

In [55]:

사각형 = 5
탐색가능지역 = 3

지뢰밭 = [[1, 0, 0, 1, 0],
          [0, 1, 0, 0, 1],
          [0, 0, 0, 1, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 1, 0, 0]]



In [56]:
import numpy as np

arr = np.array(지뢰밭)


In [57]:
arr[0:3, 0:3].sum

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [58]:
arr[0:3, 0:3].sum()

2

In [61]:
arr

array([[1, 0, 0, 1, 0],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [62]:
print(arr[0:3, 0:3])
print(arr[0:3, 1:4])
print(arr[0:3, 2:5])

print(arr[1:4, 0:3])
print(arr[1:4, 1:4])
print(arr[1:4, 2:5])




[[1 0 0]
 [0 1 0]
 [0 0 0]]
[[0 0 1]
 [1 0 0]
 [0 0 1]]
[[0 1 0]
 [0 0 1]
 [0 1 0]]


In [71]:
사각형 = 5
탐색가능지역 = 3

지뢰밭 = [[1, 0, 0, 1, 0],
          [0, 1, 0, 0, 1],
          [0, 0, 0, 1, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 1, 0, 0]]
arr = np.array(지뢰밭)
answer = []
for i in range(사각형 - 탐색가능지역 + 1):
    for j in range(사각형 - 탐색가능지역 + 1):
        answer.append(arr[i:(i+탐색가능지역), j:(j+탐색가능지역)].sum())

max(answer)

3

In [38]:
# 라이브러리 사용금지

answer = [[1, 0, 0],
          [0, 1, 0],
          [0, 0, 0]]

# sum(answer) # error
sum(answer, [])
sum(sum(answer, []))

# 문제77 : 가장 긴 공통 부분 문자열

가장 긴 공통 부분 문자열(Longest Common Subsequence)이란 A, B 두 문자열이 주어졌을 때
두 열에 공통으로 들어 있는 요소로 만들 수 있는 가장 긴 부분열을 말합니다.
여기서 부분열이란 다른 문자열에서 몇몇의 문자가 빠져 있어도 순서가 바뀌지 않은 열을 말합니다.

예를 들어 S1 = ['T', 'H', 'E', 'S', 'T', 'R', 'I', 'N', 'G', 'S']  S2 = ['T', 'H', 'I', 'S', 'I', 'S']라는 두 문자열이 있을 때
둘 사이의 부분 공통 문자열의 길이는 ['T', 'H', 'S', 'T', 'I', 'S'] 의 6개가 됩니다.

이처럼 두 문자열이 주어지면 가장 긴 부분 공통 문자열의 길이를 반환하는 프로그램을 만들어 주세요.

두 개의 문자열이 한 줄에 하나씩 주어집니다.
문자열은 알파벳 대문자로만 구성되며 그 길이는 100글자가 넘어가지 않습니다.

출력은 이 두 문자열의 가장 긴 부분 공통 문자열의 길이를 반환하면 됩니다.
```
- Test Case -

입력
THISISSTRINGS
THISIS

출력
6

-

입력
THISISSTRINGS
TATHISISKKQQAEW

출력
6

-

입력
THISISSTRINGS
KIOTHIKESSISKKQQAEW

출력
3

-

입력
THISISSTRINGS
TKHKIKSIS

출력
3
```

# 문제78 : 원형테이블

In [92]:
from collections import deque


n = 6
f = 2
food = list(range(1, n+1))
food

[1, 2, 3, 4, 5, 6]

In [ ]:
food_r = deque(food)
food_r.popleft()
food_r.rotate(-2)
food_r

In [98]:
food_r = deque(food)
print(f'먹은 음식: {food_r.popleft()}')
food_r.rotate(-2)
print(f'회전 후: {food_r}')

print(f'먹은 음식: {food_r.popleft()}')
food_r.rotate(-2)
print(f'회전 후: {food_r}')

print(f'먹은 음식: {food_r.popleft()}')
food_r.rotate(-2)
print(f'회전 후: {food_r}')

deque([4, 5, 6, 2, 3])

In [104]:
from collections import deque
def solution(n, k):
    food = range(1, n+1)
    food_r = deque(food)

    while len(food_r) > 2:
        food_r.popleft()
        food_r.rotate(-(k-1))
    return list(food_r)
solution(6, 3)

[3, 5]

# 문제79 : 순회하는 리스트

# 문제80 : 순열과 조합

# 문제81 : 지뢰찾기

```
데이터
flag = [] #지뢰 없이 깃발만 있는 리스트
minesweeper = [] #지뢰를 찾은 리스트
for i in range(5):
    flag.append(input('깃발 값과 함께 입력하세요 :').split(' '))

pass
print(flag)
print(minesweeper)



입력
0 1 0 0 0
0 0 0 0 0
0 0 0 1 0
0 0 1 0 0
0 0 0 0 0

출력
* f * 0 0
0 * 0 * 0
0 0 * f *
0 * f * 0
0 0 * 0 0

```

In [114]:
import numpy as np

matrix = [
    [0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 0, 1, 0]
]

matrix_arr = np.array(matrix)
matrix_arr = np.where(matrix_arr==1, 'f', matrix_arr)

for v, h in zip(np.where(matrix_arr=='f')[0], np.where(matrix_arr=='f')[1]):
    if v != 0:
        matrix_arr[v-1, h] = '*'
    if h != 0:
        matrix_arr[v, h-1] = '*'
    if v+1 < matrix_arr.shape[0]:
        matrix_arr[v+1, h] = '*'
    if h+1 < matrix_arr.shape[1]:
        matrix_arr[v, h+1] = '*'

print(matrix_arr)

[['*' 'f' '*' '0' '0']
 ['0' '*' '0' '*' '0']
 ['0' '0' '*' 'f' '*']
 ['0' '*' 'f' '*' '0']
 ['0' '0' '*' 'f' '*']]
